---
title: "Title"
author: "Names Here"
date: "`r format(Sys.time(),'%m-%d-%Y')`"
format: 
  html:
    embed-resources: true
knitr:
  opts_chunk:
    echo: true
    message: false
    warning: false
    error: true
    R.options:
      digits: 3
      max.print: 20
---

```{r}
# It's a good idea to load all packages in one chunk
library(tidyverse)
```

```{r}
ggplot(penguins, aes(x = flipper_len, y = bill_dep, color = species)) +
  geom_point() +
  geom_smooth(method = "lm", se = FALSE) +
  labs(
    x = "Flipper length (mm)",
    y = "Bill depth (mm)",
    color = "Species"
  ) +
  theme_bw()

# This will save the plot in the figures folder so you can add it to your paper or presentation
ggsave("figures/penguins-regression-plot.png", width = 4, height = 4, units = "in")
```

For this example bill depth is my response variable and species is one of my explanatory variables. If your explanatory variable is numeric, you don't need to do the `group_by()`.

```{r}
penguins |> 
  group_by(species) |> 
  summarize(
    mean(bill_dep, na.rm = TRUE), 
    sd(bill_dep, na.rm = TRUE), 
    n()
  ) |> 
  knitr::kable(
    col.names = c(
      "Species",
      "Mean", 
      "Standard Deviation", 
      "Number"
    )
  )
```


